### ISSUE TITLE
RFE: audit time changes via the adjtimex(2) syscall

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-kernel#10]
The adjtimex syscall takes a pointer to a structure as its argument. We have to be able to audit when someone or something changes the system clock because that affects correlation of events. Auditing this syscall floods the audit trail with  status requests.

**Comment by WOnder93** [comment]
I think I could try to implement this. I suppose we should add a new auxiliary record type (say `AUDIT_ADJ_TIME`) and emit such record every time adjtimex() gets (successfully) called in a non-read-only mode. @pcmoore, would that work for you? Or would it be better to always emit a record that would have some kind of 'readonly=yes/no' field?

One question though is what information we should add to that record (if any). Perhaps a mask of what is changed? Maybe also to what value(s)?

**Comment by WOnder93** [comment]
> @WOnder93 I'm going to assign this to you, but if you would prefer this not be assigned let me know and I'll update the issue.

No, that's fine, that's exactly what I wanted :)

> As far as the additional record is concerned, yes, I think adding a new record with the time information is likely the best course of action. Although please check to first ensure that such a record type doesn't already exist (I suspect the answer is "no").

I already had a quick look and couldn't find one, I'll double-check before I begin.

> With respect to when the new record is generated, I think the best thing to do is only to generate the record when the caller attempts to change the system's value. If an administrator is interested in all time accesses they can just log the related syscalls.

Ack.

**Comment by WOnder93** [comment]
Initial patchset posted upstream for discussion:
https://www.redhat.com/archives/linux-audit/2018-June/msg00095.html

**Comment by WOnder93** [comment]
v2 patchset: https://www.redhat.com/archives/linux-audit/2018-June/msg00114.html
v3 patchset: https://www.redhat.com/archives/linux-audit/2018-July/msg00001.html

**Comment by WOnder93** [comment]
v4 patchset: https://www.redhat.com/archives/linux-audit/2018-August/msg00023.html

**Comment by WOnder93** [comment]
v5 patchset: https://www.redhat.com/archives/linux-audit/2018-August/msg00039.html

**Comment by WOnder93** [comment]
v6 patchset: https://www.redhat.com/archives/linux-audit/2019-March/msg00016.html
RFE page: https://github.com/linux-audit/audit-kernel/wiki/RFE-More-detailed-auditing-of-changes-to-system-clock

**Comment by WOnder93** [comment]
v8: https://www.redhat.com/archives/linux-audit/2019-April/msg00074.html
Now [merged](https://github.com/linux-audit/audit-kernel/compare/7e8eda734d30de81d06a949c9bf9853c445ede4e%5E%5E...7e8eda734d30de81d06a949c9bf9853c445ede4e) into audit/next.
