### ISSUE TITLE
RFE: support for v3 namespaced file capabilities

### ISSUE THREAD

**Issue by stevegrubb** [linux-audit/audit-kernel#103]
V3 namespaced file capabilities was introduced a while back. See commit 8db6c34f1dbc8e06aa016a9b829b06902c3e1340.  It adds a uid field. I'd suggest a new field name of rootid. It won't affect anything to append this to the end of the record.

Also, it appears that effective capabilities are not part of the file system. So, I don't know why this field is recorded.

**Comment by rgbriggs** [comment]
On 2019-01-04 09:02, Steve Grubb wrote:
> Also, it appears that effective capabilities are not part of the file system. So, I don't know why this field is recorded.

There is an effective bit encoded in the magic_etc field using the VFS_CAP_FLAGS_EFFECTIVE mask.  The version is in the top 8 bits of 32 while the effective bit is in the bottom bit of 32.

**Comment by rgbriggs** [comment]
Post v1:
https://www.redhat.com/archives/linux-audit/2019-January/msg00085.html
https://lkml.org/lkml/2019/1/23/948

**Comment by rgbriggs** [comment]
Staged in audit/next v5.0-rc1: 2fec30e245a3 ("audit: add support for fcaps v3")

**Comment by rgbriggs** [comment]
Upstreamed in Linux v5.0.  Please close.
