### ISSUE TITLE
RFE: remove unused actx parameter from audit_rule_match

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-kernel#107]
The audit_rule_match() struct audit_context *actx parameter is not used by any in-tree consumers (selinux, apparmour, integrity, smack).

The audit context is an internal audit structure that should only be accessed by audit accessor functions.
It was part of commit 03d37d25e0f9 ("LSM/Audit: Introduce > generic Audit LSM hooks") but appears to have never been used.

It should be removed.  See (brief) discussion: https://www.redhat.com/archives/linux-audit/2019-January/msg00130.html

**Comment by rgbriggs** [comment]
Post v1 patch to linux-audit, lsm, lkml:
https://www.redhat.com/archives/linux-audit/2019-January/msg00134.html
https://lkml.org/lkml/2019/1/31/690

**Comment by pcmoore** [comment]
@rgbriggs assigning to you for obvious reasons, feel free to object.

**Comment by rgbriggs** [comment]
Staged upstream in audit/next v5.0-rc1: 90462a5bd30c ("audit: remove unused actx param from audit_rule_match")
