### ISSUE TITLE
BUG: connect AUDIT_LOGIN record to its syscall event

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-kernel#110]
Currently the AUDIT_LOGIN event is a standalone record that isn't connected to any other records that may be part of its syscall event.  To avoid the confusion of generating two events, this record should be connected by using the audit_context() call rather than NULL.

**Comment by pcmoore** [comment]
We've treated similar issues as bugs haven't we?  For example, look at the other issue you recently filed (#109) which considers a similar issue as a bug.

**Comment by rgbriggs** [comment]
On 2019-03-12 06:48, Paul Moore wrote:
> We've treated similar issues as bugs haven't we?  For example, look at
> the other issue you recently filed (#109) which considers a similar
> issue as a bug.

Yes, that's a very reasonable argument.

- RGB

--
Richard Guy Briggs <rgb@redhat.com>
Sr. S/W Engineer, Kernel Security, Base Operating Systems
Remote, Ottawa, Red Hat Canada
IRC: rgb, SunRaycer
Voice: +1.647.777.2635, Internal: (81) 32635

**Comment by rgbriggs** [comment]
Posted v1:
https://www.redhat.com/archives/linux-audit/2019-March/msg00080.html

**Comment by rgbriggs** [comment]
2019-03-19: Posted v1:
https://www.redhat.com/archives/linux-audit/2019-March/msg00080.html

2019-03-20: merged into audit/next:
73e65b88feb9 audit: connect LOGIN record to its syscall record

**Comment by rgbriggs** [comment]
Upstreamed: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=02aff8db6438ce29371fd9cd54c57213f4bb4536
