### ISSUE TITLE
RFE: get rid of unnecessary list_empty() checks in auditfilter and auditsc code

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-kernel#112]
The original conditions that led to the use of list_empty() to optimize list_for_each_entry_rcu() in auditfilter.c and auditsc.c code are no longer present, so remove the unnecessary list_empty() call.

**Comment by pcmoore** [comment]
FWIW, I consider this a RFE, not a BUG.

**Comment by rgbriggs** [comment]
Staged in audit/next: 699c1868a743 audit: purge unnecessary list_empty calls

**Comment by rgbriggs** [comment]
Upstreamed: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=02aff8db6438ce29371fd9cd54c57213f4bb4536
