### ISSUE TITLE
BUG: accompanying records missing for requried records when no rules present

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-kernel#120]
When there are no audit rules registered, mandatory records (config, etc.) are missing their accompanying records (syscall, proctitle, etc.).

This is due to audit context dummy set on syscall entry based on absence of rules that signals that no other records are to be printed.

**Comment by rgbriggs** [comment]
Post v1.0
https://www.redhat.com/archives/linux-audit/2020-February/msg00061.html
https://lkml.org/lkml/2020/2/18/1087

**Comment by rgbriggs** [comment]
post v2:
https://www.redhat.com/archives/linux-audit/2020-March/msg00026.html
https://lkml.org/lkml/2020/3/10/970

**Comment by rgbriggs** [comment]
Upstreamed 2020-03-12 for 5.6-rc1 1320a4052ea1

**Comment by rgbriggs** [comment]
NULL pointer dereference reported by bauen1:
- https://lore.kernel.org/linux-audit/4bee5a4a-cb1b-6db7-6c41-fb5221b5363c@gmail.com/T/#t
- https://www.redhat.com/archives/linux-audit/2020-July/msg00079.html

Reproducer:
- echo "(auditallow systemd_logind_t file_type (dir (all)))" > mytest.cil && sudo semodule -i mytest.cil
- clear all rules in /etc/audit/audit.rules and /etc/audit/rules.d/
- reboot

Mitigated by: [ghak96](https://github.com/linux-audit/audit-kernel/issues/96)
commit d7481b24b816 ("audit: issue CWD record to accompany LSM_AUDIT_DATA_* records")

Code audit still needed to check all other records generated from audit_log_exit().

**Comment by rgbriggs** [comment]
Post v3fix:
https://www.redhat.com/archives/linux-audit/2020-July/msg00132.html
https://lkml.org/lkml/2020/7/27/1692

**Comment by rgbriggs** [comment]
v2 reverted from audit/stable-5.8
https://www.redhat.com/archives/linux-audit/2020-July/msg00144.html
8ac68dc455d9 revert: 1320a4052ea1 ("audit: trigger accompanying records when no rules present")
https://www.redhat.com/archives/linux-audit/2020-July/msg00170.html

**Comment by rgbriggs** [comment]
post v4:
https://www.redhat.com/archives/linux-audit/2020-September/msg00041.html                                                                           
https://patchwork.kernel.org/patch/11768033

**Comment by rgbriggs** [comment]
post v5:
https://www.redhat.com/archives/linux-audit/2020-September/msg00052.html                                                                           
https://lkml.org/lkml/2020/9/22/481
https://patchwork.kernel.org/patch/11792463/

**Comment by rgbriggs** [comment]
v5.7-rc1
1320a4052ea1  audit: trigger accompanying records when no rules present
v5.9-rc1
d7481b24b816  audit: issue CWD record to accompany LSM_AUDIT_DATA_* records
v5.8
8ac68dc455d9  revert: 1320a4052ea1 ("audit: trigger accompanying records when no rules present")
audit/next
6d915476e67d audit: trigger accompanying records when no rules present

**Comment by rgbriggs** [comment]
On 2020-12-16 18:28, Paul Moore wrote:
> Reopened #120.

I was going to say...  It isn't in Linus' tree yet, which is why I didn't ask to have it closed yet.  :-)

**Comment by pcmoore** [comment]
Yes, I was on a bit of a roll closing out issues and this was a case of my finger clicking on the "Close" button while my mind was still reading the last update :)

**Comment by rgbriggs** [comment]
In v5.11-rc1 2020-12-27, in v5.11 2021-02-14
