### ISSUE TITLE
BUG: inconsistent 32-bit x86 SOCKETCALL auditing on 32-bit and 64-bit kernels

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-kernel#14]
See the linux-audit mail list thread for details:
- https://www.redhat.com/archives/linux-audit/2016-May/msg00010.html

**Comment by jikk** [comment]
any update on this issue?

**Comment by rgbriggs** [comment]
None yet.

**Comment by rgbriggs** [comment]
Other half of thread (cut off by list archive sw): 
    https://www.redhat.com/archives/linux-audit/2016-May/msg00019.html
Test program source code: conn.c: 
    https://www.redhat.com/archives/linux-audit/2016-May/binl9WGBWeApX.bin

**Comment by rgbriggs** [comment]
Reproduced on:
  rawhide - 4.8.0-0.rc4.git4.1.fc26.x86_64
  f25 - 4.8.0-0.rc4.git0.1.fc25.x86_64
  f22 - 4.6.0-+.x86_64
  RHEL7.2 - 3.10.0-537+.el7.test.x86_64.debug
  RHEL6.8 - 2.6.32-642.11.1.el6.x86_64

Works as expected on:
  RHEL6.6 - 2.6.32-642.4.2.el6.i686
  Debian 7.7 - 3.2.0-4-686-pae

A delay of 1s and a sync was required after triggering the rule before calling ausearch.

**Comment by rgbriggs** [comment]
@jikk How are you assured that the binary you are running on your x86_64 system is 32-bit?

Can you use the file(1) tool to report the binary details for conn on each of your 32-bit and 64-bit systems please?

The reason I ask is that without extra flags, I believe that gcc will create a 64-bit binary when run on a 64-bit system if you don't include the -m32 or -mx32 flags, and a binary created on a 32-bit system that you intend to run on the 64-bit system would most likely need a gcc --static argument to avoid issues finding the exact shared libraries.

**Comment by rgbriggs** [comment]
Found root cause: net/compat.c:sys_socketcall() is missing the call to audit_socketcall() as in net/socket.c:sys_socketcall().  The fix will be a bit tricky because the arguments need to be translated from 32 bits to 64 bits somewhere around copy_from_user().

**Comment by rgbriggs** [comment]
Correction: net/compat.c:compat_sys_socketcall()

**Comment by rgbriggs** [comment]
Posted patch: https://www.redhat.com/archives/linux-audit/2017-January/msg00055.html

**Comment by rgbriggs** [comment]
Posted upstream:
  https://www.mail-archive.com/netdev@vger.kernel.org/msg147664.html
  https://lkml.org/lkml/2017/1/13/153
  https://www.redhat.com/archives/linux-audit/2017-January/msg00061.html
Updated test case:
  https://github.com/rgbriggs/audit-testsuite/commit/898caccd3df37fda3234253b83fb5089d6e7c9e7

**Comment by rgbriggs** [comment]
2017-01-13: posted v2 upstream to netdev, lkml, linux-audit:
    https://www.redhat.com/archives/linux-audit/2017-January/msg00061.html

2017-01-17: posted v3 upstream to netdev, lkml, linux-audit, davem ack:
    https://www.redhat.com/archives/linux-audit/2017-January/msg00082.html

**Comment by pcmoore** [comment]
Merged via 62bc306e2083436675e33b5bdeb6a77907d35971.

**Comment by rgbriggs** [comment]
Fixup update to ignore harmless error in test  case pushed to https://github.com/rgbriggs/audit-testsuite/commit/681e94a892332ddd444e614a56bd9d81c15baf4d
