### ISSUE TITLE
Q: elogind stops incrementing session ID after some uptime

### ISSUE THREAD

**Issue by opty77** [linux-audit/audit-kernel#142]
[elogind stops incrementing session ID after some uptime](https://www.linuxquestions.org/questions/slackware-14/elogind-stops-incrementing-session-id-after-some-uptime-4175722822)

elogind or audit login session ID bug?

**Comment by pcmoore** [comment]
The audit session ID is incremented whenever a valid UID is successfully written to "/proc/self/loginuid", see `audit_set_loginuid()` and `proc_loginuid_write()` in the Linux Kernel sources for more information.  Generally this is handled at login via the "pam_loginuid" PAM module, I suggest you start there to figure out what might be going wrong as the kernel code hasn't changed in some time and there are no widespread reports of breakages.

* https://man7.org/linux/man-pages/man8/pam_loginuid.8.html

**Comment by pcmoore** [comment]
It's generally considered a good idea to copy the relevant information into the GH issue.  You can still provide a link to the external source, but it's helpful if all of the relevant information is contained within the GH issue itself.

Looking quickly at the external issue, it looks like this issue has been resolved as a configuration issue so I'm going to close this out.  If you believe this is still an issue with the kernel please feel free to re-open the issue or leave an additional comment and I can re-open it.

**Comment by opty77** [comment]
Sorry, I didn't want to duplicate but I will try to keep it in mind next time (if any).

For now it really seems like an elogind issue, thanks for your patience.
