### ISSUE TITLE
BUG: audit_exe_compare() has bugs

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-kernel#19]
See discussion upstream:

 * https://lkml.org/lkml/2016/7/31/98

**Comment by pcmoore** [comment]
@rgbriggs did you see this thread upstream?

I'm assigning this to you for obvious reasons, but we can reassign it if needed.

**Comment by rgbriggs** [comment]
Yes, I saw that thread when I got pulled into it 2nd last message and went back to look at the discussion.  I don't have a quick answer.  A timely acknowledgement if not action might be helpful on my part.  This coming week at LinuxCon might be a good opportunity to track down some of those interested.

**Comment by pcmoore** [comment]
Okay, just wanted to make sure it was on your radar.

**Comment by rgbriggs** [comment]
Posted patch upstream 2016-08-22
  https://www.redhat.com/archives/linux-audit/2016-August/msg00059.html
Counterpatch
  https://www.redhat.com/archives/linux-audit/2016-August/msg00061.html
  https://www.redhat.com/archives/linux-audit/2016-August/msg00066.html

**Comment by pcmoore** [comment]
Fixed with commits cd81a9170e69e018bbaba547c1fd85a585f5697a and 5efc244346f9f338765da3d592f7947b0afdc4b5 .
