### ISSUE TITLE
RFE: add a tty field to the AUDIT_LOGIN event

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-kernel#2]
In order to correlate an USER_AUTH event to a LOGIN event, we need to have the tty that's associated with the change in loginuid.

**Comment by pcmoore** [comment]
We should be able to record the tty information using logic similar to what we use in audit_log_task_info(), in fact it might be a good idea to split this out into a helper function, e.g. audit_get_tty().

Snippet from audit_log_task_info():

        spin_lock_irq(&tsk->sighand->siglock);
        if (tsk->signal && tsk->signal->tty && tsk->signal->tty->name)
                tty = tsk->signal->tty->name;
        else
                tty = "(none)";
        spin_unlock_irq(&tsk->sighand->siglock);

**Comment by pcmoore** [comment]
While an RFE, this is a rather minor addition and a [feature page](https://github.com/linux-audit/audit-kernel/wiki/Template-RFE) isn't required, just the usual verbose patch description.  However, as with all new changes a corresponding patch for the [test suite](https://github.com/linux-audit/audit-testsuite) will be required for kernel patch acceptance.

**Comment by rgbriggs** [comment]
Pull request for a test: https://github.com/linux-audit/audit-testsuite/pull/21/commits/a76cc13e72c6dc2ab5681868c872cedfae73c974

Posted a code patch to the mailing list: https://www.redhat.com/archives/linux-audit/2016-April/msg00072.html

**Comment by pcmoore** [comment]
FYI, @rgbriggs V4 patch was merged in as commit db0a6fb5d97afe01fd9c47d37c6daa82d4d4001d.
