### ISSUE TITLE
RFE: better error reporting when CONFIG_AUDITSYSCALL is disabled

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-kernel#20]
As described in the email thread below, it can sometimes be confusing when an admin attempts to set audit filters and syscall auditing has been disabled in the kernel.  While we already return an error to the user, it seems like we could also emit a printk(...) message indicating that support has not been compiled into the kernel; other ideas are also welcome.
- https://www.redhat.com/archives/linux-audit/2016-October/msg00000.html

**Comment by rgbriggs** [comment]
Might it be better to return -ENOTSUPP ?

**Comment by rgbriggs** [comment]
Since CONFIG_AUDITSYSCALL is now forced on with CONFIG_AUDIT, can we close this?

**Comment by pcmoore** [comment]
Sounds reasonable to me.  CLOSED.
