### ISSUE TITLE
BUG: convert references from Steve's people page to the GitHub project

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-kernel#24]
The audit source files in the kernel reference Steve's [Red Hat people page](http://people.redhat.com/sgrubb/audit) as the audit userspace utilities home.  Once @stevegrubb flips the switch and migrates the userspace repository to [linux-audit/audit-userspace](https://github.com/linux-audit/audit-userspace) we should update/remote the references in the kernel.

**Comment by rgbriggs** [comment]
References found in:
MAINTAINERS
kernel/audit.c

**Comment by pcmoore** [comment]
> Once @stevegrubb flips the switch and migrates the userspace repository to linux-audit/audit-userspace we should update/remote the references in the kernel.

The switch "has been flipped", so we can make this update now.

**Comment by pcmoore** [comment]
Updated version:
* https://www.redhat.com/archives/linux-audit/2018-February/msg00007.html

**Comment by pcmoore** [comment]
Merged via d590dca62bb8a315a2356159444de07278a3ad83
