### ISSUE TITLE
BUG: the AUDIT_MAC_POLICY_LOAD event is not well-formed

### ISSUE THREAD

**Issue by stevegrubb** [linux-audit/audit-kernel#27]
The AUDIT_MAC_POLICY_LOAD event is missing some information:

type=MAC_POLICY_LOAD msg=audit(1479299795.404:43): policy loaded auid=4294967295 ses=4294967295

There should be results even if its hard coded as success. Also, what policy version got loaded (ok if not available), which MAC framework (selinux/smack/apparmor), and uid might be useful in telling if the user had changed accounts.

**Comment by stevegrubb** [comment]
The record also has dangling text "policy loaded". That is implied by the record type and could be dropped.

**Comment by stevegrubb** [comment]
Decided to post a patch for this:
https://www.redhat.com/archives/linux-audit/2016-November/msg00025.html

**Comment by pcmoore** [comment]
Now being tracked in #47.
