### ISSUE TITLE
RFE: reset the "lost" value as seen via 'auditctl -s'

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-kernel#3]
Add the ability to clear/reset the lost value from the output of 'auditctl -s':

```
# auditctl -s
enabled 1
failure 1
pid 1025
rate_limit 0
backlog_limit 8192
lost 66
backlog 0
backlog_wait_time 60000
loginuid_immutable 0 unlocked
```

**Comment by stevegrubb** [comment]
OK, this seems like a small patch but it has a big impact. Many system admins 
have to tend to the audit trail. If they have lost events in a burst the 
counter is going to be some odd number like 876812. The next day they want to 
know if there has been any lost events since yesterday. Now they see 876814. They have to try 
to remember what yesterday's number was and do some math.

It would be easier for them if the cron job generating their daily report issues 
a command that resets the counter after running the report so the next day has correct number since yesterday without any math.

**Comment by rgbriggs** [comment]
RFC patch submitted upstream:
    https://www.redhat.com/archives/linux-audit/2016-December/msg00026.html

It still requires userspace support and a test case.

**Comment by pcmoore** [comment]
RFC v2 patch posted upstream:

* https://www.redhat.com/archives/linux-audit/2016-December/msg00064.html

**Comment by pcmoore** [comment]
Patch v3:

* https://www.redhat.com/archives/linux-audit/2016-December/msg00100.html

**Comment by pcmoore** [comment]
@rgbriggs I'm thinking this change might also warrant a RFE wiki page, what do you think?

* https://github.com/linux-audit/audit-kernel/wiki/RFE-Reset-the-Lost-Record-Counter

**Comment by pcmoore** [comment]
@stevegrubb what do you think of the new audit record in Richard's latest patch (link below)?

* https://www.redhat.com/archives/linux-audit/2016-December/msg00100.html

**Comment by rgbriggs** [comment]
I've fleshed out the RFE: https://github.com/linux-audit/audit-kernel/wiki/RFE-Reset-the-Lost-Record-Counter/3ab56b71ecff79da9d28f3b90f099b6cd5eaa6e0

**Comment by pcmoore** [comment]
Merged via 92c82e8a322b32a6cabe7d8800dc10401157a623.

@rgbriggs, please update the RFE page on the wiki to reflect the changes in the v4 patch; as soon as that is done we can closeout this issue.

**Comment by rgbriggs** [comment]
RFE updated: https://github.com/linux-audit/audit-kernel/wiki/RFE-Reset-the-Lost-Record-Counter/6825ca2ce1b2f7c316ea9003869ad7a647737df0

**Comment by rgbriggs** [comment]
Updated the RFE based on userspace implementation: https://github.com/linux-audit/audit-kernel/wiki/RFE-Reset-the-Lost-Record-Counter/e62b2f5f9855918439517227850ecf8db9185112

**Comment by rgbriggs** [comment]
Created an acceptance test: https://github.com/linux-audit/audit-testsuite/pull/41/commits/7784fa7d6a2b1879ec8bfac56247317f1d1c21be

**Comment by rgbriggs** [comment]
Test case update (reset auditd after test): https://github.com/linux-audit/audit-testsuite/pull/41/commits/101fb3a640fb90fc6d74c356e07e6879aa3e0203
