### ISSUE TITLE
RFE: add ambient capabilities to audit logs

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-kernel#40]
Capabilities were augmented to include ambient capabilities in v4.3 <58319057b7847667f0c9585b9de0e8932b0fdb08>.

Add ambient capabilities to the BPRM_FCAPS and CAPSET records.

**Comment by pcmoore** [comment]
Possibly related to #16.

**Comment by rgbriggs** [comment]
Posted upstream in lsm, linux-audit. (no link yet due to linux-audit moderation, lsm archives MIA)

Userspace:
    issue: https://github.com/linux-audit/audit-userspace/issues/16
    pullrequest: https://github.com/linux-audit/audit-userspace/pull/17

**Comment by pcmoore** [comment]
FYI: after years of fighting with the various list archive services, we finally started self-hosting an archive for the LSM list.

* http://kernsec.org/pipermail/linux-security-module-archive

**Comment by rgbriggs** [comment]
Perfect, heard such a rumour, the link works, posting still in moderation...

**Comment by rgbriggs** [comment]
Upstream posting:
  https://www.redhat.com/archives/linux-audit/2017-April/msg00029.html

**Comment by pcmoore** [comment]
Merged via 7786f6b6dfc12d17eea2df04116de6ebac50c884.
