### ISSUE TITLE
BUG: cap_* fields swing in and out of PATH record

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-kernel#42]
The cap_* fields swing in and out of PATH records.
If no capabilities are set, the cap_* fields are completely missing and when one of the cap_fi or cap_fp values is empty, that field is omitted.
Normalize the PATH record by always printing all 4 cap_* fields.

**Comment by rgbriggs** [comment]
Patch posted upstream: https://www.redhat.com/archives/linux-audit/2017-April/msg00128.html

**Comment by pcmoore** [comment]
Commented upstream; looks good, but needs to wait until after the v4.12 merge window for merging into audit/next.

**Comment by pcmoore** [comment]
Merged via 4b3e4ed6b0d958d7fb2f160bb8ebfb4f0db19382.

**Comment by The-Mule** [comment]
@rgbriggs is this covered in audit-testsuite?

**Comment by rgbriggs** [comment]
On 2017-10-04 03:07, Ondrej Moris wrote:
> @rgbriggs is this covered in audit-testsuite? 

I don't believe so, but it is very easy to check with:

	ausearch -i -m path|grep PATH|less

and *every* entry should have four cap_* fields, most records showing:

	cap_fp=none cap_fi=none cap_fe=0 cap_fver=0
