### ISSUE TITLE
Q: should ANOM_PROMISCUOUS be accompanied or autonomous?

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-kernel#45]
The ANOM_PROMISCUOUS record is declared with context included, attaching itself to a SYSCALL record, but it already includes some subject attributes.

Should this be an autonomous record or should it be accompanying a SYSCALL record?

Recommend either removing the subject attributes from the ANOM_PROMISCUOUS, or (preferably) making them more complete and not adding a context reference to the audit_log... call.

```
type=SYSCALL msg=audit(05/12/2017 19:11:13.254:109) : arch=x86_64 syscall=ioctl success=yes exit=0 a0=0x17 a1=SIOCBRADDIF a2=0x7fdb72d74ad0 a3=0x2 items=0 ppid=1 pid=2284 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=libvirtd exe=/usr/sbin/libvirtd subj=system_u:system_r:virtd_t:s0-s0:c0.c1023 key=(null)
type=ANOM_PROMISCUOUS msg=audit(05/12/2017 19:11:13.254:109) : dev=virbr0-nic prom=yes old_prom=no auid=unset uid=root gid=root ses=unset
```

note: net/core/dev.c:__dev_set_promiscuity()

**Comment by pcmoore** [comment]
Is it possible to change the interface promiscuity without a syscall?  I know that the interface can change promiscuity indirectly (I believe bridging and/or some other interface layering can have that effect), but all of those configuration changes should be attached to a syscall, yes?

**Comment by rgbriggs** [comment]
As far as I know, promiscuity will drop when link does, independent of user directives.

**Comment by pcmoore** [comment]
In my opinion the proper behavior would be to tie the record with the associated SYSCALL record whenever possible.

**Comment by rgbriggs** [comment]
So given the situation, nothing should be changed, since it is already associated with a syscall due to using the current->audit_context and fields can't be changed other than to append, leaving auid, uid, gid and ses duplicating those in the syscall record.
