### ISSUE TITLE
BUG: normalize AUDIT_MAC_POLICY_LOAD

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-kernel#47]
Currently the AUDIT_MAC_POLICY_LOAD record includes dangling keywords:
- security/selinux/selinuxfs.c:sel_write_load(): "policy loaded auid=%u ses=%u"

Switch "policy loaded" to "op=policy_load" or "op=load_policy".

Additionally, should auid= and ses= be dropped if this record is accompanied by a syscall record? If not, then should the context passed to audit_log() be NULL?

**Comment by pcmoore** [comment]
This appears to be a duplicate of #27, but I'll keep this one since the description is cleaner.  However, issue #27 brought up some additional points:

* Missing success field
* Missing LSM information (e.g. SELinux, Smack, AppArmor, etc.)

**Comment by pcmoore** [comment]
Also related to AUDIT_MAC_POLICY_LOAD: #62.

**Comment by rgbriggs** [comment]
From https://github.com/linux-audit/audit-kernel/issues/27 a preliminary patch was posted:
https://www.redhat.com/archives/linux-audit/2016-November/msg00025.html

**Comment by rgbriggs** [comment]
Suggest new format of: "auid=%u ses=%u lsm=%s res=1".  Policy version isn't readily available that I can tell.

**Comment by pcmoore** [comment]
From a SELinux perspective there is no policy "version" in the conventional sense.  There is a policy format version, but that is really just about the binary policy syntax and not the actual policy semantics/content.

**Comment by pcmoore** [comment]
Another note, while I don't believe this would have any impact on these tools, we would need to verify that this change would not break the `audit2allow` and `audit2why` tools.

**Comment by rgbriggs** [comment]
Posted patch upstream to linux-audit, lkml, lsm, selinux:
https://www.redhat.com/archives/linux-audit/2018-April/msg00028.html
https://lkml.org/lkml/2018/4/9/825

**Comment by rgbriggs** [comment]
Upstreamed in v4.18-rc1, released in v4.18
