### ISSUE TITLE
RFE: add additional fields for use in audit filter exclude rules

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-kernel#5]
The exclude filter was created a long time ago to filter out SELinux AVC's to meet the Common Criteria profile for CAPP. Currently the only field that can be used for filtering is the msgtype field. There are times when an admin may want to exclude events coming from user space or syscall events using uid, auid, session ID, or even SELinux types.

The lowest common denominator is the credentials that come from netlink during user space originating events. It might be possible to combine the filters for user and exclude which would give a little more flexibility in writing rules for the exclude filter. The only issue is the semantics are different between them. The user filter passes selected events where the exclude deletes selected events.

**Comment by pcmoore** [comment]
While an RFE, this is a rather minor addition and a [feature page](https://github.com/linux-audit/audit-kernel/wiki/Template-RFE) isn't required, just the usual verbose patch description.  However, as with all new changes a corresponding patch for the [test suite](https://github.com/linux-audit/audit-testsuite) will be required for kernel patch acceptance.

**Comment by pcmoore** [comment]
For reference, patch posting upstream w/discussion:

* https://www.redhat.com/archives/linux-audit/2016-June/msg00000.html

**Comment by rgbriggs** [comment]
Posted v2 patch upstream:
https://www.redhat.com/archives/linux-audit/2016-June/msg00019.html

**Comment by pcmoore** [comment]
The v4 of the patch was committed via 86b2efbe3a390e07dbba725ef700b0d143e9a385.

**Comment by rgbriggs** [comment]
An additional supporting patch was added to indicate the presence of this feature in the kernel:
"audit: add exclude filter extension to feature bitmap"
https://www.redhat.com/archives/linux-audit/2016-August/msg00037.html

**Comment by rgbriggs** [comment]
Userspace support patches were posted upstream.

A supporting prerequisite patchset for refactoring audit_get_feature() and adding support for loginuid_set from v3.10 will avoid merge conflicts:
    https://www.redhat.com/archives/linux-audit/2016-August/msg00042.html

The userspace support is in
    https://www.redhat.com/archives/linux-audit/2016-August/msg00045.html

The test case is:
    https://github.com/rgbriggs/audit-testsuite/commit/8d1d4e3b8cf781d2249dc388267b9bee6072ec6b

**Comment by rgbriggs** [comment]
@pcmoore Looks like https://www.redhat.com/archives/linux-audit/2016-August/msg00037.html is still missing upstream

**Comment by pcmoore** [comment]
Merged via 7ff89ac608d9e856cae6fa651553fa0709bf9c50
