### ISSUE TITLE
RFE: allow audit-by-executable-name not equal operator

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-kernel#53]
Upstream added audit-by-executable-name filtering using the exe= filter.
`34d99af52ad4 ("audit: implement audit by executable")`

Add negation to the operator options.

**Comment by pcmoore** [comment]
Related mailing list discussion:

* https://www.redhat.com/archives/linux-audit/2017-June/msg00029.html

**Comment by WOnder93** [comment]
@pcmoore This seems like a good task to start with, can you assign me? :)

But I'll probably need some hints here... I looked at the code briefly and I'm not really sure what needs to be changed to get this working. I will take a closer look later and try to come back with some concrete questions.

**Comment by pcmoore** [comment]
> @pcmoore This seems like a good task to start with, can you assign me? :)

Its is all yours now :)

> But I'll probably need some hints here... I looked at the code briefly and I'm not really sure what needs to be changed to get this working. I will take a closer look later and try to come back with some concrete questions.

No problem, I'll wait for your questions, but if you would prefer a quick overview first let me know.

**Comment by pcmoore** [comment]
Quick summary of the various patches.

The v2 kernel patch:

* https://www.redhat.com/archives/linux-audit/2018-April/msg00021.html

... the userspace patch:

* https://github.com/linux-audit/audit-userspace/pull/45

... and the audit-testsuite patch:

* https://github.com/linux-audit/audit-testsuite/pull/67

**Comment by rgbriggs** [comment]
Upstream since 4.18-rc1 23bcc48 ("audit: allow not equal op for audit by executable")
