### ISSUE TITLE
RFE: deprecate the audit entry filter

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-kernel#6]
The audit entry filter is deprecated and should be removed. There was a plan to remove it around the 2.6.31 time frame, but that was missed.

**Comment by rgbriggs** [comment]
Posted patch upstream:
  https://www.redhat.com/archives/linux-audit/2018-February/msg00013.html
  https://lkml.org/lkml/2018/2/7/204

**Comment by rgbriggs** [comment]
Posted v2 patchset upstream:
https://www.redhat.com/archives/linux-audit/2018-February/msg00016.html

**Comment by rgbriggs** [comment]
Squashed patches 1&2, posted v3 patchset upstream:
https://www.redhat.com/archives/linux-audit/2018-February/msg00040.html
https://lkml.org/lkml/2018/2/14/975

**Comment by pcmoore** [comment]
Merged via 5260ecc2e0480cc7e184901ab4c3721d0c2765e3 and 94d14e3e7b41d99f0d62a41fd856183057e1e474

**Comment by rgbriggs** [comment]
@pcmoore I assume this can be closed now?
