### ISSUE TITLE
BUG: the kernel does not initialize audit before forking PID 1

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-kernel#66]
The kernel needs to initialize the audit subsystem before forking init/systemd so that the audit subsystem can allocate an audit_context for the process, enabling the collection of audit data if configured (e.g. `audit=1` on the kernel command line).

The current audit code is initialized via the generic kernel initcall mechanism, which is eventually called *after* the kernel forks PID 1 (PID 1 -> kernel_init(...) -> kernel_init_freeable(...) -> do_basic_setup(...) -> do_initcalls(...)).  We most likely want to add a call to audit_init(...) before key_init(...) or security_init(...) in start_kernel(...).

**Comment by pcmoore** [comment]
Quick note: calling audit_init() from start_kernel() means we will need to split the kauditd_thread creation into a separate init function that we call from the normal initcall mechanism.

**Comment by pcmoore** [comment]
Another update: it looks like we want to keep most of audit_init() in the code called via the normal initcall mechanism (although maybe use subsys_initcall), and simply set audit_enabled and audit_ever_enabled in the new early init.

**Comment by pcmoore** [comment]
It looks like I have a preliminary patch which boots, solves the problem, and doesn't appear to break anything at first glance.  Let me play around with it a bit more and I'll post it.

In case anyone is wondering, this isn't likely to go into audit/next before the upcoming merge window.

**Comment by pcmoore** [comment]
After looking at the patch a bit more, I decided to just move the logic into audit_enable(...) (as it only matters if `audit=1` is passed on the kernel's command line) since it makes the patch much cleaner and less intrusive.

I'm also playing with a few other patches to go into the patchset which would clean up some variable types, the strtol usage, and move audit_init(...) earlier in the initcall process.

**Comment by pcmoore** [comment]
Upstream RFC patchset posting is linked below.  It's a five patch set, but strictly speaking only patch 1/5 is necessary to fix the problem, the other four patches just make things less sucky.

* https://www.redhat.com/archives/linux-audit/2017-September/msg00002.html
* https://www.redhat.com/archives/linux-audit/2017-September/msg00003.html

**Comment by rgbriggs** [comment]
I know this was working properly at some point.  This patch 1/5 restores previous behaviour and that this wasn't all useless code after all that was removed in this previous commit in v3.14-rc1 (2014-02-02):
        d3ca0344b21f04786219bf0f49647f24e4e17323 gaofeng 2013-10-31
        ("audit: remove useless code in audit_enable")

**Comment by pcmoore** [comment]
FYI, the RFC patchset mentioned above is now in audit/next and should go up to Linus during the next merge window.

**Comment by pcmoore** [comment]
Patches merged via 5d842a5b77a58160625548fa6be2dc159179ffdb b3b4fdf6a8ae9ea51ea274e3f2f8a6a58b98cc0b 80ab4df62706b882922c3bb0b05ce2c8ab10828a be4104abf25c63ccef36e1e06262c73c0df9fd60 173743dd99a49c956b124a74c8aacb0384739a4c
