### ISSUE TITLE
RFE: record the module name passed to init_module(2)

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-kernel#7]
Record the module name passed as an argument to init_module(2).  A simple reproducer is shown below:

```
1. Add "-a always,exit -F arch=x86_64 -S init_module -F key=mod-load" to the audit rules
2. Reboot the system
3. Run 'ausearch --start today -k mod-load -i | less'
```

**Comment by rgbriggs** [comment]
I'm guessing the best way to do this will be with an auxiliary record other than PATH.  Module name is in kernel/module.c:load_module():mod->name

**Comment by rgbriggs** [comment]
The current format of the records resulting from an init_module syscall monitor is:
type=PROCTITLE msg=audit(01/19/2017 20:49:06.317:159) : proctitle=/sbin/modprobe -q -- rpc-auth-gss-390004
type=SYSCALL msg=audit(01/19/2017 20:49:06.317:159) : arch=x86_64 syscall=init_module success=yes exit=0 a0=0x55c54f292980 a1=0xcfb3 a2=0x55c54dcfb106 a3=0x0 items=0 ppid=61 pid=561 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=modprobe exe=/usr/bin/kmod subj=system_u:system_r:insmod_t:s0 key=mod-load

**Comment by rgbriggs** [comment]
Created an RFE wiki page: https://github.com/linux-audit/audit-kernel/wiki/RFE-Module-load-record-format

**Comment by pcmoore** [comment]
Quick comment on the RFE, how about calling the logging function audit\_log\_kern\_module() instead of audit\_log\_init\_module()?

**Comment by rgbriggs** [comment]
That's a good idea.  I was considering calling it audit_log_module_load...  And also considering the possibility of modules being unloaded and trying to leave the terminology open enough to accomodate that in the same type of record format for example, by using an "op=load" field...

**Comment by rgbriggs** [comment]
Posted RFC patch upstream to lkml and linux-audit:
https://www.redhat.com/archives/linux-audit/2017-January/msg00113.html

**Comment by pcmoore** [comment]
I'm reviewing the upstream RFC posting now, but one consistency nit jumped out at me ... capitalize the words in RFE wiki page (see the existing RFE wiki pages).  Not a big deal, but since we are still in the feedback loop stage we might as well rename the wiki page.

**Comment by rgbriggs** [comment]
Renamed RFE wiki page:
https://github.com/linux-audit/audit-kernel/wiki/RFE-Module-Load-Record-Format

**Comment by rgbriggs** [comment]
Updated the RFE wiki page to:
- change from audit_module_init() to audit_log_kern_module
- change from AUDIT_MODULE_INIT to AUDIT_KERN_MODULE
https://github.com/linux-audit/audit-kernel/wiki/RFE-Module-Load-Record-Format

**Comment by rgbriggs** [comment]
Commited acceptance test:
https://github.com/rgbriggs/audit-testsuite/commit/1ac48c12d76c7f152f4e35aaba84ace2436db52b

**Comment by rgbriggs** [comment]
Post V2 patch upstream:
https://www.redhat.com/archives/linux-audit/2017-February/msg00012.html

**Comment by pcmoore** [comment]
Merged via 5a8ef9207155fb70f1737a22bc4a1209ca539ece.

**Comment by pcmoore** [comment]
Correction, merged via ca86cad7380e373fa17bc0ee8aff121380323e69.

**Comment by rgbriggs** [comment]
Pull request: https://github.com/linux-audit/audit-testsuite/pull/44

**Comment by rgbriggs** [comment]
This new pull request is a minor update to the original test and the addition of another patch that augments it to test unload module too.

**Comment by rgbriggs** [comment]
https://github.com/linux-audit/audit-testsuite/pull/46

**Comment by rgbriggs** [comment]
Updated RFE to add ghak37
