### ISSUE TITLE
RFE: group all audit task parameters together

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-kernel#81]
Move all audit-related task parameters out of struct task_struct into a dedicated structure allocated at task creation.  At the moment this includes loginuid, sessionid and audit_context.

**Comment by rgbriggs** [comment]
Paul, please assign to me...

**Comment by pcmoore** [comment]
@rgbriggs it might be nice to provide a link to the mailing list discussion for this, or at the very least copy-n-past the relevant portions here.

**Comment by rgbriggs** [comment]
On 2018-04-25 11:28, Paul Moore wrote:
> @rgbriggs it might be nice to provide a link to the mailing list discussion for this, or at the very least copy-n-past the relevant portions here.

See discussion started here:
	https://www.redhat.com/archives/linux-audit/2018-April/msg00055.html
and continuing here:
	https://www.redhat.com/archives/linux-audit/2018-April/msg00094.html

**Comment by rgbriggs** [comment]
2018-05-04: Posted v1 patchset (static alloc)
https://www.redhat.com/archives/linux-audit/2018-May/msg00038.html
https://lkml.org/lkml/2018/5/4/793

2018-05-12: Posted v2 patchset (static alloc)
https://www.redhat.com/archives/linux-audit/2018-May/msg00067.html
https://lkml.org/lkml/2018/5/12/173

2018-05-14: Merged upstream:
v2p2: f0b7521 ("audit: convert sessionid unset to a macro")
v2p3: cdfb6b3 ("audit: use inline function to get audit context")
v2p4: c0b0ae8 ("audit: use inline function to set audit context")

2018-05-16: Posted v3 patchset (dynamic alloc)
https://www.redhat.com/archives/linux-audit/2018-May/msg00088.html
https://lkml.org/lkml/2018/5/16/461

**Comment by rgbriggs** [comment]
2018-05-17: Merged upstream:
v3p1: 8982a1f ("audit: use new audit_context access funciton for seccomp_actions_logged")
v3p2: 38f8059 ("audit: normalize loginuid read access")
v3p3: blocked on ghak32 (containerid)

**Comment by pcmoore** [comment]
As discussed on the mailing list, this is really only going to go in with the audit container ID work so let's close this out and just use issue #90 since this issue doesn't make sense by itself any longer.
